#!/usr/bin/env node

const { JavaCaller } = require("java-caller");

// java-caller moves args starting with -D/-X to the JVM; PMD's -D means --debug
const args = process.argv.slice(2).map((arg) => (arg === "-D" ? "--debug" : arg));

new JavaCaller({
  rootPath: __dirname,
  classPath: "dist/pmd-bin/lib/*",
  mainClass: "net.sourceforge.pmd.cli.PmdCli",
  minimumJavaVersion: 17,
  javaType: "jre",
})
  .run(args)
  .then(({ status, stdout, stderr }) => {
    process.stdout.write(stdout);
    if (process.env.NPM_PMD_BIN_STDERR === "true") process.stderr.write(stderr);
    process.exit(status);
  })
  .catch((err) => {
    console.error(err);
    process.exit(-1);
  });
