name: Update PMD version

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *" # daily at 9 am

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - name: Update PMD version
        id: update-pmd-version
        run: |
          export latestVersion="$(./scripts/update-pmd-version.mjs)"
          echo "latestVersion=${latestVersion}"
          echo "latestVersion=${latestVersion}" > $GITHUB_OUTPUT
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          add-paths: |
            package.json
          commit-message: "feat: update dependency pmd to ${{ steps.update-pmd-version.outputs.latestVersion }}"
          title: "feat: update dependency pmd to ${{ steps.update-pmd-version.outputs.latestVersion }}"
          branch: feat/update-pmd
