name: Update PMD version

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 * * * *" # every hour

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Update PMD version
        run: |
          export latestVersion="$(./scripts/update-pmd-version.mjs)"
          echo "latestVersion=${latestVersion}" > $GITHUB_OUTPUT
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          add-paths: |
            package.json
          commit-message: "feat: update dependency pmd to ${{ steps.update-pmd-version.latestVersion }}"
          title: "feat: update dependency pmd to ${{ steps.update-pmd-version.latestVersion }}"
          branch: feat/update-pmd
